### ISSUE TITLE
Numbering of the different bib entries

### ISSUE THREAD

**Issue by martinferianc** [pcooksey/bibtex-js#64]
Thank you very much for providing an amazing framework and a tool to organise the bibliography into nice compact lists. I was wondering whether there is an option to count the different items and have the items numbered. E.g.: I am just making a bulletpoint list: https://martinferianc.github.io/#publications and I was wondering whether I could replace the bulletpoints by numbers.

Thank you again very very much!

**Comment by rgiot** [comment]
Hello, I did it this way (reverse order numbering from most recent to less recent)

```css
	div.templates {
		counter-reset: n;
		display: flex;
		flex-direction: column-reverse;
	}
	div.bibtexentry > p:nth-child(1)::before {
		counter-increment: n;
		content: "[" counter(n) "] ";
		flex: 0 0 auto;
	}
```

```html
		<div class="bibtex_template">
					<p>
... </p></div>

<div class="bibtex_display" keywords="codelogiciel">
							<div class="bibtex_structure">
								<div class="sort year" extra="ASC number">
									<div class="templates"></div>
								</div>
							</div>
						</div>


```

of course to be adatped to your context
